name: PotionStacker
main: com.example.potionstacker.PotionStackerPlus
version: 1.0.1
api-version: 1.21
author: Cha0sBEpic
website: https://github.com/Cha0sBEpic/PotionStacker

commands:
  potionstacker:
    description: Manage potion stacking behavior
    usage: /potionstacker <reload|setstack|addeffect|removeeffect>
    permission: potionstacker.use
    permission-message: You do not have permission to use this command.

permissions:
  potionstacker.use:
    description: Allows use of the potionstacker command
    default: op
